CREATE TABLE CAOWT.CONTACT_TO_SKILL (
	contact_id INT NOT NULL,
	skill_id INT NOT NULL,
	CONSTRAINT CONTACT_TO_SKILL_PK PRIMARY KEY (contact_id,skill_id),
	CONSTRAINT CONTACT_TO_SKILL_FK FOREIGN KEY (contact_id) REFERENCES CAOWT.CONTACT(id) ON DELETE CASCADE,
	CONSTRAINT CONTACT_TO_SKILL_FK_1 FOREIGN KEY (skill_id) REFERENCES CAOWT.SKILL(id) ON DELETE CASCADE
)
COMMENT='Join table between Contact and Skill';
